### PR TITLE
Add prop: textInputProps as a dict which will be props of text input.

### PR DESCRIPTION
**Pull request by yueshuaijie**
PR for #6 .

Usage:
`
    <Prompt
        textInputProps={{
            keyboardType:'phone-pad'
        }}
    />
`

### CODE REVIEW

**Comment by joonhocho** [comment]
+1

**Comment by codepujan** [comment]
+1

**Comment by stereodenis** [comment]
@jaysoo ?

**Comment by jaysoo** [comment]
Thanks @yueshuaijie

**Comment by codepujan** [comment]
@jaysoo @yueshuaijie  What would be the appropriate Prop value for   Numeric Input. (0-9) ?

**Comment by yueshuaijie** [comment]
@codepujan I believe it should be 'number-pad'.

**Pull request merged**
