### PR TITLE
remove Portal dep, fix jaysoo/react-native-prompt#3 and fix jaysoo/re…

### PR DESCRIPTION
**Pull request by sibelius**
…act-native-prompt#1 on example

### CODE REVIEW

**Comment by sibelius** [comment]
please test on android device

**Comment by sibelius** [comment]
cc @tonyxiao

**Comment by rturk** [comment]
Hi @jaysoo can you merge this and publish a new release? tks

**Comment by tonyxiao** [comment]
👍

**Comment by jaysoo** [comment]
Thanks @sibelius @tonyxiao sorry for the delay

**Comment by jaysoo** [comment]
@sibelius @tonyxiao @rturk Just published 0.18.5 and verified everything is okay with react-native 0.27.2

**Pull request merged**
